// This file is automatically generated. Do not edit it directly.

const BACKEND_URL = process.env.VITE_BACKEND_URL || '';
const BACKEND_PUBLISHABLE_KEY = process.env.VITE_BACKEND_PUBLISHABLE_KEY || '';

// Import the backend client like this:
// import { myBackend } from "@/integrations/backend/client";

// Placeholder custom backend client
class CustomBackendClient {
  constructor(url: string, key: string) { }

  from(table: string) {
    return {
      select: (query: string) => ({
        order: (col: string, options?: any) => Promise.resolve({ data: [], error: null }),
      }),
      insert: (data: any) => Promise.resolve({ data: null, error: null })
    };
  }

  functions = {
    invoke: (fnName: string, options?: any) => Promise.resolve({ data: { content: 'This is a mock response.', latency_ms: 100 }, error: null })
  };
}

export const myBackend = new CustomBackendClient(BACKEND_URL, BACKEND_PUBLISHABLE_KEY);